name       : palapeli
version    : 18.08.3
release    : 2
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.3/src/palapeli-18.08.3.tar.xz : 289744cff0d3d0f01cc0f1c31c26e330f44cf3e0925c3ee6750cf232631ecf18
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : A single-player jigsaw puzzle game
description: |
    A single-player jigsaw puzzle game
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdoctools-devel
    - kio-devel
    - ki18n-devel
    - knotifications-devel
    - libkdegames-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
