name       : palapeli
version    : 20.12.1
release    : 30
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/palapeli-20.12.1.tar.xz : b50baa4eb6bfb0c0d987195276eddd740d8bc38667f6f7d0f911bc653570a315
homepage   : https://kde.org/applications/games/org.kde.palapeli
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : A single-player jigsaw puzzle game
description: |
    A single-player jigsaw puzzle game
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - karchive-devel
    - kcrash-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - libkdegames-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
