name       : palapeli
version    : 19.08.2
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/palapeli-19.08.2.tar.xz : bae810595c7ba7bdac0fa5c27e6c2a3a9bb1bbdae3521cfc036ec0cdcd9ef1a7
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : A single-player jigsaw puzzle game
description: |
    A single-player jigsaw puzzle game
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - karchive-devel
    - kcrash-devel
    - kdoctools-devel
    - kio-devel
    - ki18n-devel
    - knotifications-devel
    - libkdegames-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
