name       : palapeli
version    : 21.08.3
release    : 40
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/palapeli-21.08.3.tar.xz : 0be25ee2d17018a825115e4461b7e65cbae9b7705f3c9dcfd9b9ceffb6da9620
homepage   : https://kde.org/applications/games/org.kde.palapeli
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : A single-player jigsaw puzzle game
description: |
    A single-player jigsaw puzzle game
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - karchive-devel
    - kcrash-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - libkdegames-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
