name       : palapeli
version    : 23.04.1
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/palapeli-23.04.1.tar.xz : 403bf461a2027800ba555afa9c9624d61dfa17764a75cfd49f121dad7c4ab229
homepage   : https://kde.org/applications/games/org.kde.palapeli
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : A single-player jigsaw puzzle game
description: |
    A single-player jigsaw puzzle game
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - karchive-devel
    - kcrash-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - libkdegames-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
