name       : palapeli
version    : 22.08.3
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/palapeli-22.08.3.tar.xz : 2f5337c5e5519d25be7de083bb4eb2122dd3a63d2cd0bb46927db304fa839b18
homepage   : https://kde.org/applications/games/org.kde.palapeli
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : A single-player jigsaw puzzle game
description: |
    A single-player jigsaw puzzle game
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - karchive-devel
    - kcrash-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - libkdegames-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
