name       : palapeli
version    : 18.12.1
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.1/src/palapeli-18.12.1.tar.xz : 0ddfb2a0123b10fac4e41683ca41a3b2b42b0b6f9be4510b0aaebb65ada58e5f
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : A single-player jigsaw puzzle game
description: |
    A single-player jigsaw puzzle game
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdoctools-devel
    - kio-devel
    - ki18n-devel
    - knotifications-devel
    - libkdegames-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
