name       : palapeli
version    : 20.12.2
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/palapeli-20.12.2.tar.xz : 7c46d34e167d5183aebe99be5e9608640450dc762c2a4377390f9afb444200fd
homepage   : https://kde.org/applications/games/org.kde.palapeli
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : A single-player jigsaw puzzle game
description: |
    A single-player jigsaw puzzle game
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - karchive-devel
    - kcrash-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - libkdegames-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
